version: "3.9"
services:
  cerbos:
    container_name: cerbos
    image: ghcr.io/cerbos/cerbos:latest
    restart: always
    command: ["server", "--config=/config/conf.yaml", "--log-level=warn"]
    volumes:
      - ./cerbos/config:/config
      - ./cerbos/policies:/policies
    ports:
      - 3592:3592
      - 3593:3593
    networks:
      - intranet
  database:
    image: mysql
    volumes:
      - mysqldb:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=core
      - MYSQL_DATABASE=cerbos
      - MYSQL_USER=core
      - MYSQL_PASSWORD=core
    ports:
    - "3306:3306" 
    networks:
      - intranet
 
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: "no"
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=core@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=core
  #   ports:
  #     - "5433:80"
  #   networks:
  #     - intranet
  admin-api:
    container_name: admin-api
    build: .
    environment:
      - CERBOS_HOST=cerbos
    ports:
      - 8080:8080
    depends_on:
      - cerbos
      - database
    networks:
      - intranet


networks:
  intranet:
volumes:
  mysqldb:
    name: vol-mysqldb
